dist: xenial
language: python
python: 2.7
virtualenv:
  system_site_packages: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:fontforge/fontforge'
    packages:
      - fontforge
      - python-fontforge
      - texlive-xetex
      - poppler-utils

install:
  - pip install -r requirements.txt

script:
  - make -j4
  - make -j4 check
